//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GradesPrototype
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public System.Guid UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string ImageName { get; set; }
        public Nullable<System.Guid> TeacherUserId { get; set; }
    
        public virtual User User { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
